ENCODER_ENABLE = yes
ENCODER_MAP_ENABLE = yes

EXTRAKEY_ENABLE = yes
REPEAT_KEY_ENABLE = yes
LAYER_LOCK_ENABLE = yes

OLED_ENABLE = yes
RGBLIGHT_ENABLE = no
RGB_MATRIX_ENABLE = no
CONSOLE_ENABLE = no
